### ISSUE TITLE
requirements.txt doesn't install

### ISSUE THREAD

**Issue by jmafoster1** [CITCOM-project/causcumber#11]
From the root directory, when I run `pip install -r requirements.txt` I get the error
```
ERROR: git+git@github.com:microsoft/dowhy.git@56c0b347295587a11fb98b9bec4b8d27962e6a5c#egg=dowhy is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
```
I have no idea what I'm doing with python requirements so I'm not really sure how to fix it.

**Comment by AndrewC19** [comment]
I have changed the requirement for DoWhy in requirements.txt. That should prevent this error from ocurring in the future but will install the latest release of DoWhy which has buggy confidence intervals.
